import type { components } from "./contracts.generated";
export type { paths, components } from "./contracts.generated";
export type StageManifest = components["schemas"]["StageManifest"];
export type Lease = components["schemas"]["Lease"];
export type WorkerEvent = components["schemas"]["WorkerEvent"];
export type Snapshot = components["schemas"]["Snapshot"];
export type ScenarioDocument = components["schemas"]["ScenarioDocument"];
export type RunSettings = components["schemas"]["RunSettings"];
export type RunSummary = components["schemas"]["RunSummary"];
export type ExplorerSettings = components["schemas"]["ExplorerSettings"];
export type ExplorerSummary = components["schemas"]["ExplorerSummary"];
export type ContractName = "StageManifest" | "WorkerEvent" | "Snapshot" | "Lease" | "ScenarioDocument" | "RunSettings" | "RunSummary" | "ExplorerSettings" | "ExplorerSummary";
