import { watch } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';

// Generates src/registry/__index__.tsx: a lazy component per example and chart,
// so a docs page only loads the previews it renders. `--watch` regenerates on change.
const root = new URL('../src/registry/', import.meta.url);
const dirs = ['examples', 'charts'];

async function entries(dir) {
  const files = (await readdir(new URL(dir, root))).filter((f) => f.endsWith('.tsx')).sort();
  return Promise.all(
    files.map(async (file) => {
      const name = file.replace(/\.tsx$/, '');
      const src = await readFile(new URL(`${dir}/${file}`, root), 'utf8');
      const named = src.match(/export function (\w+)/)?.[1];
      const exported = /export default/.test(src) ? 'default' : named;
      if (!exported) throw new Error(`${dir}/${file} has no component export`);
      return { name, path: `${dir}/${name}`, exported };
    }),
  );
}

function render(all) {
  const lines = all.map(
    (e) =>
      `  ${JSON.stringify(e.name)}: lazy(() => import('./${e.path}').then((m) => ({ default: m.${e.exported} }))),`,
  );
  return `// Generated by scripts/registry.mjs. Do not edit.
'use client';

import { lazy, type ComponentType, type LazyExoticComponent } from 'react';

export const previews: Record<string, LazyExoticComponent<ComponentType>> = {
${lines.join('\n')}
};
`;
}

async function generate() {
  const all = (await Promise.all(dirs.map(entries))).flat();
  const target = new URL('__index__.tsx', root);
  const out = render(all);
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== out) await writeFile(target, out);
  console.log(`registry: ${all.length} previews`);
}

await generate();

if (process.argv.includes('--watch')) {
  let timer;
  for (const dir of dirs) {
    watch(new URL(dir, root), () => {
      clearTimeout(timer);
      timer = setTimeout(() => generate().catch((error) => console.error(error.message)), 100);
    });
  }
}
